# Site settings
title: Adaway for Windows
description: by 천상의나무
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adaway for Windows
user_description: Adaway for Windows 는 hosts 파일을 이용한 완전 무료 광고차단 프로그램입니다. 
user_title: Windows 를 위한 오픈 소스 광고 차단 프로그램.
email: ajb8533296@gmail.com
# twitter_username: lorem_ipsum
github_username:  NewPremium
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
